### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by nathsimpson**
Install ESLINT, and a basic GitHub Action, as well as resolve any eslint errors

### CODE REVIEW

**Comment by Noviny** [comment]
The lack of eslint was more a feature than a bug - what’s the reason for wanting to add these?

**Comment by nathsimpson** [comment]
@Noviny Immediate reason was for developing the website, but also for any further things we might add to this repo.

**Comment by nathsimpson** [comment]
This PR has been here for a while. Happy to close it if it's not wanted :)

**Comment by elisechant** [comment]
Hey @nathsimpson, this is great initiative, I was looking for the linter too! 

It would be great if you could improve this PR by aiming for a slightly lighter touch. 

What I mean by this is: 
* have as few eslint packages as possible
* perhaps include "eslint-config-prettier" and "eslint-plugin-prettier"
* remove prop-types additions
* aim for a lighter .eslintrc

Potentially also: 
* add git hook to run format or lint on push

**Comment by nathsimpson** [comment]
Thanks for finding this. I hadn't seen touched this in over a year!
Great suggestions, I have addressed your feedback

**Comment by elisechant** [comment]
@nathsimpson I just deleted the `origin/website` branch, can you please reopen against `origin/master`?

**Pull request closed without merging**
